"""updating models

Revision ID: 0ac56b5ea41c
Revises: e067c6657db8
Create Date: 2025-12-20 13:45:39.699134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.base

# revision identifiers, used by Alembic.
revision: str = '0ac56b5ea41c'
down_revision: Union[str, Sequence[str], None] = 'e067c6657db8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_degree',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_degree_name'), 'master_degree', ['name'], unique=False)
    op.create_table('master_education',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_education_name'), 'master_education', ['name'], unique=False)
    op.create_table('master_experience_level',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_experience_level_name'), 'master_experience_level', ['name'], unique=False)
    op.create_table('master_job_category',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_job_category_name'), 'master_job_category', ['name'], unique=False)
    op.create_table('master_skill',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_skill_name'), 'master_skill', ['name'], unique=False)
    op.add_column('candidates', sa.Column('dob', sa.Date(), nullable=True))
    op.add_column('candidates', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('candidates', sa.Column('gender', sa.String(length=20), nullable=True))
    op.add_column('candidates', sa.Column('education', sa.JSON(), nullable=True))
    op.add_column('candidates', sa.Column('degree', sa.JSON(), nullable=True))
    op.add_column('company_payments', sa.Column('remarks', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('degree', sa.JSON(), nullable=True))
    op.add_column('jobs', sa.Column('gender', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'gender')
    op.drop_column('jobs', 'degree')
    op.drop_column('company_payments', 'remarks')
    op.drop_column('candidates', 'degree')
    op.drop_column('candidates', 'education')
    op.drop_column('candidates', 'gender')
    op.drop_column('candidates', 'age')
    op.drop_column('candidates', 'dob')
    op.drop_index(op.f('ix_master_skill_name'), table_name='master_skill')
    op.drop_table('master_skill')
    op.drop_index(op.f('ix_master_job_category_name'), table_name='master_job_category')
    op.drop_table('master_job_category')
    op.drop_index(op.f('ix_master_experience_level_name'), table_name='master_experience_level')
    op.drop_table('master_experience_level')
    op.drop_index(op.f('ix_master_education_name'), table_name='master_education')
    op.drop_table('master_education')
    op.drop_index(op.f('ix_master_degree_name'), table_name='master_degree')
    op.drop_table('master_degree')
    # ### end Alembic commands ###
