"""updated candidate field

Revision ID: 14e8107d9edf
Revises: 083aa9ba7917
Create Date: 2025-12-21 00:42:42.458175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14e8107d9edf'
down_revision: Union[str, Sequence[str], None] = '083aa9ba7917'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('experience_level', sa.String(length=20), nullable=True))
    op.drop_column('candidates', 'experience_years')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('experience_years', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('candidates', 'experience_level')
    # ### end Alembic commands ###
