"""joc to cource change

Revision ID: 98621c511ead
Revises: 19fec14638bd
Create Date: 2025-12-31 12:07:33.941790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app.models.base

# revision identifiers, used by Alembic.
revision: str = '98621c511ead'
down_revision: Union[str, Sequence[str], None] = '19fec14638bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_structure_fees',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('candidate_id', app.models.base.GUID(), nullable=False),
    sa.Column('total_fee', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_structure_fees_candidate_id'), 'course_structure_fees', ['candidate_id'], unique=False)
    op.drop_index(op.f('ix_joc_structure_fees_candidate_id'), table_name='joc_structure_fees')
    op.drop_table('joc_structure_fees')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('joc_structure_fees',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('candidate_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('total_fee', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('balance', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('due_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('joc_structure_fees_candidate_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('joc_structure_fees_pkey'))
    )
    op.create_index(op.f('ix_joc_structure_fees_candidate_id'), 'joc_structure_fees', ['candidate_id'], unique=False)
    op.drop_index(op.f('ix_course_structure_fees_candidate_id'), table_name='course_structure_fees')
    op.drop_table('course_structure_fees')
    # ### end Alembic commands ###
