"""initial migrations

Revision ID: e067c6657db8
Revises: 
Create Date: 2025-12-17 21:15:53.818046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.models.base

# revision identifiers, used by Alembic.
revision: str = 'e067c6657db8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_company_category',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_company_category_name'), 'master_company_category', ['name'], unique=False)
    op.create_table('master_location',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_location_name'), 'master_location', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('candidates',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('mobile_number', sa.String(length=20), nullable=True),
    sa.Column('qualification', sa.Text(), nullable=True),
    sa.Column('experience_years', sa.Float(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('resume_url', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('expected_salary', sa.Integer(), nullable=True),
    sa.Column('location_area_id', app.models.base.GUID(), nullable=True),
    sa.Column('job_preferences', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('employment_status', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_area_id'], ['master_location.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_candidates_email'),
    sa.UniqueConstraint('mobile_number', name='uq_candidates_mobile_number')
    )
    op.create_index(op.f('ix_candidates_employment_status'), 'candidates', ['employment_status'], unique=False)
    op.create_index('ix_candidates_location_area_id', 'candidates', ['location_area_id'], unique=False)
    op.create_index(op.f('ix_candidates_status'), 'candidates', ['status'], unique=False)
    op.create_table('companies',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('category_id', app.models.base.GUID(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('location_area_id', app.models.base.GUID(), nullable=True),
    sa.Column('contact_person', sa.Text(), nullable=True),
    sa.Column('contact_number', sa.String(length=20), nullable=True),
    sa.Column('alternate_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('google_map_url', sa.Text(), nullable=True),
    sa.Column('location_link', sa.Text(), nullable=True),
    sa.Column('visiting_card_url', sa.Text(), nullable=True),
    sa.Column('front_image_url', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', app.models.base.GUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('verification_status', sa.Boolean(), nullable=False),
    sa.Column('company_status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['master_company_category.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['location_area_id'], ['master_location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_category_id'), 'companies', ['category_id'], unique=False)
    op.create_index(op.f('ix_companies_company_status'), 'companies', ['company_status'], unique=False)
    op.create_index(op.f('ix_companies_location_area_id'), 'companies', ['location_area_id'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_table('files',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('mimetype', sa.String(length=255), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('uploaded_by', app.models.base.GUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_payments',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('candidate_id', app.models.base.GUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_candidate_payments_amount_positive'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_candidate_payments_candidate_id', 'candidate_payments', ['candidate_id'], unique=False)
    op.create_index('ix_candidate_payments_payment_date', 'candidate_payments', ['payment_date'], unique=False)
    op.create_table('company_payments',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('company_id', app.models.base.GUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_company_payments_amount_positive'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_company_payments_company_id', 'company_payments', ['company_id'], unique=False)
    op.create_index('ix_company_payments_payment_date', 'company_payments', ['payment_date'], unique=False)
    op.create_table('jobs',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('company_id', app.models.base.GUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('qualification', sa.Text(), nullable=True),
    sa.Column('experience', sa.Text(), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('num_vacancies', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('responsibilities', sa.Text(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('education', sa.JSON(), nullable=True),
    sa.Column('location_area_id', app.models.base.GUID(), nullable=True),
    sa.Column('contact_person', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('num_vacancies >= 0', name='ck_jobs_num_vacancies_positive'),
    sa.CheckConstraint('salary_min IS NULL OR salary_max IS NULL OR salary_min <= salary_max', name='ck_jobs_salary_bounds'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['location_area_id'], ['master_location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_company_id', 'jobs', ['company_id'], unique=False)
    op.create_index('ix_jobs_status', 'jobs', ['status'], unique=False)
    op.create_index('ix_jobs_title', 'jobs', ['title'], unique=False)
    op.create_table('joc_structure_fees',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('candidate_id', app.models.base.GUID(), nullable=False),
    sa.Column('total_fee', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_joc_structure_fees_candidate_id'), 'joc_structure_fees', ['candidate_id'], unique=False)
    op.create_table('interviews',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('company_id', app.models.base.GUID(), nullable=False),
    sa.Column('job_id', app.models.base.GUID(), nullable=False),
    sa.Column('candidate_id', app.models.base.GUID(), nullable=False),
    sa.Column('interview_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_interviews_candidate_id', 'interviews', ['candidate_id'], unique=False)
    op.create_index('ix_interviews_company_id', 'interviews', ['company_id'], unique=False)
    op.create_index('ix_interviews_interview_date', 'interviews', ['interview_date'], unique=False)
    op.create_index('ix_interviews_job_id', 'interviews', ['job_id'], unique=False)
    op.create_index('ix_interviews_status', 'interviews', ['status'], unique=False)
    op.create_table('joined_candidates',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('job_id', app.models.base.GUID(), nullable=False),
    sa.Column('candidate_id', app.models.base.GUID(), nullable=False),
    sa.Column('Date_of_joining', sa.DateTime(timezone=True), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_joined_candidates_candidate_id', 'joined_candidates', ['candidate_id'], unique=False)
    op.create_index('ix_joined_candidates_job_id', 'joined_candidates', ['job_id'], unique=False)
    op.create_table('placement_incomes',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('interview_id', app.models.base.GUID(), nullable=False),
    sa.Column('candidate_id', app.models.base.GUID(), nullable=False),
    sa.Column('job_id', app.models.base.GUID(), nullable=False),
    sa.Column('total_receivable', sa.Integer(), nullable=False),
    sa.Column('total_received', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('total_receivable > 0', name='ck_placement_incomes_total_receivable_positive'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_placement_incomes_candidate_id', 'placement_incomes', ['candidate_id'], unique=False)
    op.create_index('ix_placement_incomes_due_date', 'placement_incomes', ['due_date'], unique=False)
    op.create_index('ix_placement_incomes_interview_id', 'placement_incomes', ['interview_id'], unique=False)
    op.create_index('ix_placement_incomes_job_id', 'placement_incomes', ['job_id'], unique=False)
    op.create_table('placement_income_payments',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('placement_income_id', app.models.base.GUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('paid_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_placement_income_payments_amount_positive'),
    sa.ForeignKeyConstraint(['placement_income_id'], ['placement_incomes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_placement_income_payments_income_id', 'placement_income_payments', ['placement_income_id'], unique=False)
    op.create_index('ix_placement_income_payments_paid_date', 'placement_income_payments', ['paid_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_placement_income_payments_paid_date', table_name='placement_income_payments')
    op.drop_index('ix_placement_income_payments_income_id', table_name='placement_income_payments')
    op.drop_table('placement_income_payments')
    op.drop_index('ix_placement_incomes_job_id', table_name='placement_incomes')
    op.drop_index('ix_placement_incomes_interview_id', table_name='placement_incomes')
    op.drop_index('ix_placement_incomes_due_date', table_name='placement_incomes')
    op.drop_index('ix_placement_incomes_candidate_id', table_name='placement_incomes')
    op.drop_table('placement_incomes')
    op.drop_index('ix_joined_candidates_job_id', table_name='joined_candidates')
    op.drop_index('ix_joined_candidates_candidate_id', table_name='joined_candidates')
    op.drop_table('joined_candidates')
    op.drop_index('ix_interviews_status', table_name='interviews')
    op.drop_index('ix_interviews_job_id', table_name='interviews')
    op.drop_index('ix_interviews_interview_date', table_name='interviews')
    op.drop_index('ix_interviews_company_id', table_name='interviews')
    op.drop_index('ix_interviews_candidate_id', table_name='interviews')
    op.drop_table('interviews')
    op.drop_index(op.f('ix_joc_structure_fees_candidate_id'), table_name='joc_structure_fees')
    op.drop_table('joc_structure_fees')
    op.drop_index('ix_jobs_title', table_name='jobs')
    op.drop_index('ix_jobs_status', table_name='jobs')
    op.drop_index('ix_jobs_company_id', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_company_payments_payment_date', table_name='company_payments')
    op.drop_index('ix_company_payments_company_id', table_name='company_payments')
    op.drop_table('company_payments')
    op.drop_index('ix_candidate_payments_payment_date', table_name='candidate_payments')
    op.drop_index('ix_candidate_payments_candidate_id', table_name='candidate_payments')
    op.drop_table('candidate_payments')
    op.drop_table('files')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_location_area_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_company_status'), table_name='companies')
    op.drop_index(op.f('ix_companies_category_id'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_candidates_status'), table_name='candidates')
    op.drop_index('ix_candidates_location_area_id', table_name='candidates')
    op.drop_index(op.f('ix_candidates_employment_status'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_master_location_name'), table_name='master_location')
    op.drop_table('master_location')
    op.drop_index(op.f('ix_master_company_category_name'), table_name='master_company_category')
    op.drop_table('master_company_category')
    # ### end Alembic commands ###
